export enum PermissionsEnum {
  'LocationEdit' = 'LocationEdit',
  'FloorEdit' = 'FloorEdit',
  'BuildingTypeRead' = 'BuildingTypeRead',
  'TariffRead' = 'TariffRead',
  'TariffEdit' = 'TariffEdit',
  'FloorRead' = 'FloorRead',
  'MeterRead' = 'MeterRead',
  'DocumentationEdit' = 'DocumentationEdit',
  'BuildingTypeEdit' = 'BuildingTypeEdit',
  'BuildingRead' = 'BuildingRead',
  'RoomRead' = 'RoomRead',
  'DocumentEdit' = 'DocumentEdit',
  'MeterSnapshotRead' = 'MeterSnapshotRead',
  'SupplyContractRead' = 'SupplyContractRead',
  'MeterSnapshotEdit' = 'MeterSnapshotEdit',
  'SupplyContractEdit' = 'SupplyContractEdit',
  'MeterEdit' = 'MeterEdit',
  'RoomEdit' = 'RoomEdit',
  'LocationRead' = 'LocationRead',
  'BuildingEdit' = 'BuildingEdit'
}
