export const basePermissionsConfig: string[] = [
  'user',
  'invite',
  'group',
  'overview',
  'profile',
  'security',
  'additional',
  'general',
  'readings',
  'environmental-readings',
  'members',
  'rights',
  // 'subordinates',
];
